2023-03-31 15:41:37 INFO Retry attempt failed:
Traceback (most recent call last):
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Miniconda3\envs\torch_gpu\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Miniconda3\envs\torch_gpu\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Miniconda3\envs\torch_gpu\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\wandb\sdk\internal\internal_api.py", line 243, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Miniconda3\envs\torch_gpu\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2023-03-31 19:22:05 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2023-03-31 19:22:05 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2023-04-03 01:46:37 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2023-04-03 01:46:56 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2023-04-25 20:35:19 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2023-04-25 20:35:51 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2023-04-25 23:14:48 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2023-04-25 23:14:48 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2023-04-25 23:14:48 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2023-05-02 00:02:38 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2023-05-02 00:02:39 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
